apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-template.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sample-template.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports: {{ range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "sample-template.selectorLabels" . | nindent 4 }}
